

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: FirstJob
      steps:
      - bash: echo build first job
      - bash: echo $(PipelivelevelVariable)
    - job: secondJob
      steps:
      - bash: echo build second job
  - stage: DevDeploy
    variables:
      environment: Dev
    dependsOn: Build
    jobs:
    - job: DevDeployJob
      steps:
      - bash: echo build DevDeployJob
  - stage: QADeploy
    variables:
      environment: QA
    dependsOn: DevDeploy
    jobs:
    - job: QADeployJob
      steps:
      - bash: echo build QADeployJob
  - stage: ProdDeploy
    variables:
      environment: Prod
    dependsOn: 
    - DevDeploy
    - QADeploy
    jobs:
    - job: ProdDeployJob
      steps:
      - bash: echo build ProdDeployJob
