

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: FirstJob
      Steps:
      - bash: echo build first job
    - job: secondJob
      steps:
      - bash: echo build second job
  - stage: DevDeploy
    jobs:
    - job: DevDeployJob
      steps:
      -bash: echo build DevDeployJob
  - stage: QADeploy
    jobs:
    - job: QADeployJob
      steps:
      -bash: echo build QADeployJob
  - stage: ProdDeploy
    jobs:
    - job: ProdDeployJob
      steps:
      -bash: echo build ProdDeployJob

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
